#!/bin/bash -f
#SBATCH --job-name='Jsh2'
#
#SBATCH --partition=savio
#
# Accout:
#SBATCH --account=co_aiolos
#
# QoS (running a condo job)
#SBATCH --qos=savio_lowprio
#
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=20
#
# Wall clock limit:
#SBATCH --time=24:00:00
#
# Mail me for any notification
#SBATCH --mail-type=all
#SBATCH --mail-user=azare@berkeley.edu
mpirun -np 160 ./wrf.exe 
