! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : radm2_Parameters.f90
! Time                 : Sun Sep 21 23:10:55 2014
! Working directory    : /scratch1/lcvalin/RUN/04KM_WRFV3/chem/KPP/mechanisms/radm2
! Equation file        : radm2.kpp
! Output root filename : radm2
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE radm2_Parameters

  USE radm2_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 65 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 63 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 58 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 2 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 159 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 64 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 599 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 686 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 64 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 
! PI - Value of pi
  REAL(kind=dp), PARAMETER :: PI = 3.14159265358979 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_SULF = 1 
  INTEGER, PARAMETER :: ind_ORA1 = 2 
  INTEGER, PARAMETER :: ind_ORA2 = 3 
  INTEGER, PARAMETER :: ind_JUNK = 4 
  INTEGER, PARAMETER :: ind_LCH4 = 5 
  INTEGER, PARAMETER :: ind_LMHP = 6 
  INTEGER, PARAMETER :: ind_PO3 = 7 
  INTEGER, PARAMETER :: ind_CO2 = 8 
  INTEGER, PARAMETER :: ind_SO2 = 9 
  INTEGER, PARAMETER :: ind_ETH = 10 
  INTEGER, PARAMETER :: ind_O1D = 11 
  INTEGER, PARAMETER :: ind_HC5 = 12 
  INTEGER, PARAMETER :: ind_HC8 = 13 
  INTEGER, PARAMETER :: ind_TOL = 14 
  INTEGER, PARAMETER :: ind_XYL = 15 
  INTEGER, PARAMETER :: ind_TPAN = 16 
  INTEGER, PARAMETER :: ind_HONO = 17 
  INTEGER, PARAMETER :: ind_H2O2 = 18 
  INTEGER, PARAMETER :: ind_HC3 = 19 
  INTEGER, PARAMETER :: ind_N2O5 = 20 
  INTEGER, PARAMETER :: ind_CH4 = 21 
  INTEGER, PARAMETER :: ind_PAA = 22 
  INTEGER, PARAMETER :: ind_O3P = 23 
  INTEGER, PARAMETER :: ind_OP1 = 24 
  INTEGER, PARAMETER :: ind_HNO4 = 25 
  INTEGER, PARAMETER :: ind_CSL = 26 
  INTEGER, PARAMETER :: ind_PAN = 27 
  INTEGER, PARAMETER :: ind_OL2 = 28 
  INTEGER, PARAMETER :: ind_HNO3 = 29 
  INTEGER, PARAMETER :: ind_CO = 30 
  INTEGER, PARAMETER :: ind_OLT = 31 
  INTEGER, PARAMETER :: ind_ISO = 32 
  INTEGER, PARAMETER :: ind_OLI = 33 
  INTEGER, PARAMETER :: ind_DCB = 34 
  INTEGER, PARAMETER :: ind_GLY = 35 
  INTEGER, PARAMETER :: ind_XNO2 = 36 
  INTEGER, PARAMETER :: ind_KET = 37 
  INTEGER, PARAMETER :: ind_MGLY = 38 
  INTEGER, PARAMETER :: ind_TOLP = 39 
  INTEGER, PARAMETER :: ind_XYLP = 40 
  INTEGER, PARAMETER :: ind_OLTP = 41 
  INTEGER, PARAMETER :: ind_OLN = 42 
  INTEGER, PARAMETER :: ind_XO2 = 43 
  INTEGER, PARAMETER :: ind_OL2P = 44 
  INTEGER, PARAMETER :: ind_HCHO = 45 
  INTEGER, PARAMETER :: ind_TCO3 = 46 
  INTEGER, PARAMETER :: ind_OP2 = 47 
  INTEGER, PARAMETER :: ind_HC5P = 48 
  INTEGER, PARAMETER :: ind_HC8P = 49 
  INTEGER, PARAMETER :: ind_O3 = 50 
  INTEGER, PARAMETER :: ind_ONIT = 51 
  INTEGER, PARAMETER :: ind_ALD = 52 
  INTEGER, PARAMETER :: ind_OLIP = 53 
  INTEGER, PARAMETER :: ind_ETHP = 54 
  INTEGER, PARAMETER :: ind_OH = 55 
  INTEGER, PARAMETER :: ind_HC3P = 56 
  INTEGER, PARAMETER :: ind_ACO3 = 57 
  INTEGER, PARAMETER :: ind_HO2 = 58 
  INTEGER, PARAMETER :: ind_NO3 = 59 
  INTEGER, PARAMETER :: ind_KETP = 60 
  INTEGER, PARAMETER :: ind_NO = 61 
  INTEGER, PARAMETER :: ind_NO2 = 62 
  INTEGER, PARAMETER :: ind_MO2 = 63 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_H2O = 64 
  INTEGER, PARAMETER :: ind_M = 65 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_M = 2 

END MODULE radm2_Parameters

